name: gnas
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _pytorch_select=0.1=cpu_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - astroid=2.6.6=py39h06a4308_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - ca-certificates=2022.3.18=h06a4308_0
  - certifi=2021.5.30=py39h06a4308_0
  - cffi=1.15.0=py39hd667e15_1
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cython=0.29.24=py39h295c915_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py39he80948d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.4=h295c915_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - importlib-metadata=4.8.2=py39h06a4308_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2019.4=243
  - ipykernel=6.4.1=py39hef51801_0
  - ipython=7.28.0=py39hef51801_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.0=py39hf3d152e_2
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py39h06a4308_7
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py39hf3d152e_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - lazy-object-proxy=1.6.0=py39h27cfd23_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libmklml=2019.0.5=0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuuid=1.0.3=h7f8727e_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - markupsafe=2.0.1=py39h27cfd23_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mccabe=0.6.1=py39h06a4308_1
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py39he8ac12f_0
  - mkl_fft=1.3.0=py39h54f3939_0
  - mkl_random=1.0.2=py39h63df603_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.3.0=py39h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=hff7bd54_1
  - notebook=6.4.8=py39h06a4308_0
  - numpy-base=1.19.2=py39h2ae0177_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.2.4=py37h06a4308_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pylint=2.9.6=py39h06a4308_1
  - pyqt=5.9.2=py39h2531618_6
  - pyrsistent=0.18.0=py39heee7806_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyzmq=19.0.2=py39hb69f2a1_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.2.2=pyhd3eb1b0_0
  - qtpy=1.11.2=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py39h06a4308_0
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - terminado=0.13.1=py39h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py39h3811e60_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021d=he74cb21_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - wrapt=1.12.1=py39he8ac12f_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.15.0
    - antlr4-python3-runtime==4.8
    - cachetools==4.2.4
    - charset-normalizer==2.0.6
    - colorama==0.4.4
    - commonmark==0.9.1
    - concorde==0.1.2
    - cpython==0.0.6
    - cupy-cuda111==9.5.0
    - cycler==0.10.0
    - dgl-cu111==0.6.1
    - fastrlock==0.6
    - google-auth==2.3.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.41.1
    - h5py==3.4.0
    - hydra-core==1.1.1
    - hydra-joblib-launcher==1.1.5
    - idna==3.2
    - ipdb==0.13.9
    - jinja2==3.0.2
    - joblib==1.0.1
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.4.3
    - networkx==2.6.3
    - numpy==1.21.2
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python==4.5.5.62
    - pandas==1.3.5
    - pathlib==1.0.1
    - pillow==8.3.2
    - protobuf==3.18.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymongo==3.12.1
    - pyparsing==2.4.7
    - pyrss2gen==1.1
    - pytz==2021.3
    - pyyaml==5.4.1
    - randaugment==1.0.2
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rich==10.11.0
    - rsa==4.7.2
    - scikit-learn==1.0
    - scipy==1.7.1
    - seaborn==0.11.2
    - sklearn==0.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - threadpoolctl==2.2.0
    - torch==1.9.1
    - torch-tb-profiler==0.3.1
    - torchaudio==0.9.1
    - torchvision==0.10.1
    - tqdm==4.62.3
    - urllib3==1.26.7
    - werkzeug==2.0.2

